- name: "BO"
  color: "1D76DB"
  description: "Business Office"
- name: "DC"
  color: "1D76DB"
  description: "Data Center"
- name: "DM"
  color: "924679"
  description: "Data Movement"
- name: "DBaaS"
  color: "c6acf9"
  description: "Database as a Service"
- name: "CaaS"
  color: "e5e569"
  description: "Compute as a Service"
- name: "GaaS"
  color: "018AB8"
  description: "Governance as a Service"
- name: "OB"
  color: "39E891"
  description: "Observability"
- name: "DTE"
  color: "5FDDF7"
  description: "DevOps Technical Enablement"
- name: "DX"
  color: "17AEF0"
  description: "Developer Experience"
- name: "KaaS"
  color: "b60205"
  description: "Kubernetes as a Service"
- name: "BunnyWork :rabbit:"
  color: "D4C5F9"
  description: "Archigeers"
- name: "SRE"
  color: "FF5733"
  description: "Site Reliability Engineering"
- name: "Rogue One"
  color: "80c932"
  description: "Squad"
- name: "The Second Order"
  color: "80c932"
  description: "Squad"
- name: "Phenoms"
  color: "80c932"
  description: "Squad"
- name: "Gold4"
  color: "80c932"
  description: "Squad"
- name: "GeekGurus"
  color: "80c932"
  description: "Squad"
- name: "Tech Hawks"
  color: "80c932"
  description: "Squad"
- name: "Squad 007"
  color: "80c932"
  description: "Squad"
- name: "Crazy 8"
  color: "80c932"
  description: "Squad"
- name: "District 9"
  color: "80c932"
  description: "Squad"
- name: "Ctl-Alt-Complete"
  color: "80c932"
  description: "Squad"
- name: "Oceans11"
  color: "80c932"
  description: "Squad"
- name: "Squad 12"
  color: "80c932"
  description: "Squad"
- name: "Squad-dc"
  color: "80c932"
  description: "Data Center Squad"
- name: "Squad-bo"
  color: "80c932"
  description: "Business Office Squad"
- name: "KubeGeek"
  color: "A17372"
  description: "Squad"
- name: "epic"
  color: "10d17d"
  description: "Large work item that need to be prioritized and breakdown"
- name: "Points: 0"
  color: "FEF2C0"
  description: "The size of work estimated for implementation"
- name: "Points: 1"
  color: "FEF2C0"
  description: "The size of work estimated for implementation"
- name: "Points: 2"
  color: "FEF2C0"
  description: "The size of work estimated for implementation"
- name: "Points: 3"
  color: "FEF2C0"
  description: "The size of work estimated for implementation"
- name: "Points: 5"
  color: "FEF2C0"
  description: "The size of work estimated for implementation"
- name: "Work Type: 1. Gather requirements and evaluate alt"
  color: "FEF2C0"
  description: "Labor capitalization"
- name: "Work Type: 2. Initiative planning and coordination"
  color: "FEF2C0"
  description: "Labor capitalization"  
- name: "Work Type: 3. Install configure or test Hardware"
  color: "FEF2C0"
  description: "Labor capitalization"  
- name: "Work Type: 4a. Code-Test-Deploy Internal Software"
  color: "FEF2C0"
  description: "Labor capitalization"
- name: "Work Type: 4b. Configure or test 3rd party SW"
  color: "FEF2C0"
  description: "Labor capitalization"  
- name: "Work Type: 5. Data migration and maint"
  color: "FEF2C0"
  description: "Labor capitalization"  
- name: "Work Type: 6. Incident defect support analysis"
  color: "FEF2C0"
  description: "Labor capitalization"  
- name: "Work Type: 7. Reduce Technical Debt"
  color: "FEF2C0"
  description: "Labor capitalization"    
- name: "Feature Type: 1. Technology Refresh or Capacity"
  color: "D3B1A1"
  description: "Labor capitalization" 
- name: "Feature Type: 2. Real Estate and Station Start Up"
  color: "D3B1A1"
  description: "Labor capitalization" 
- name: "Feature Type: 3. Security and Compliance"
  color: "D3B1A1"
  description: "Labor capitalization" 
- name: "Feature Type: 4. Cloud Migration with Rewrite"
  color: "D3B1A1"
  description: "Labor capitalization" 
- name: "Feature Type: 5. Cloud Migration (Lift Shift)"
  color: "D3B1A1"
  description: "Labor capitalization" 
- name: "Feature Type: 6. Tech Debt Breakfix and Maint"
  color: "D3B1A1"
  description: "Labor capitalization" 
- name: "Feature Type: 7. Add new BU OKR functionality"
  color: "D3B1A1"
  description: "Labor capitalization" 
- name: "Feature Type: 8. Tech 2.0 and DT"
  color: "D3B1A1"
  description: "Labor capitalization"               
- name: "bug"
  color: "E99695"
  description: "A Bug for a Product in the Organization"
- name: "service-request"
  color: "e6f7a3"
  description: "A Service Request for a Product in the Organization"
- name: "feature-request"
  color: "e4e669"
  description: "A Feature Request for a Product in the Organization"
- name: "blocked"
  color: "B60205"
  description: "Issue is blocked"
- name: "question"
  color: "C2E0C6"
  description: "Quick Question"
- name: "cepdocs"
  color: "3FC30B"
  description: "Good candidate for addition to CEPDOCs"
