name: Create TnT Labels

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
    paths:
    - '.github/ISSUE_TEMPLATE/labels.yml'

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/crazy-max/ghaction-github-labeler
      # Manage labels as code
      - name: Run Labeler
        uses: aadependencies/ghaction-github-labeler@v3.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/ISSUE_TEMPLATE/labels.yml
          skip-delete: true
          dry-run: false
          exclude: |
            help*
            *issue
